// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Tag$ReactTemplate = require("./Tag.bs.js");
var TagsData$ReactTemplate = require("./TagsData.bs.js");

var component = ReasonReact.reducerComponent("AllTags");

function make(tagsUrl, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var handlePostsLoaded = Curry._1(self[/* reduce */1], (function (tagsData) {
                      return /* Loaded */[tagsData];
                    }));
              TagsData$ReactTemplate.fetchTags(tagsUrl).then((function (tagsData) {
                      Curry._1(handlePostsLoaded, tagsData);
                      return Promise.resolve(/* () */0);
                    }));
              return /* NoUpdate */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */2][/* tagsData */0];
              var tags = match ? $$Array.map((function (tag) {
                        return ReasonReact.element(/* None */0, /* None */0, Tag$ReactTemplate.make(tag, /* array */[]));
                      }), match[0]) : "Loading...";
              return React.createElement("div", {
                          className: "display"
                        }, tags);
            }),
          /* initialState */(function () {
              return /* record */[/* tagsData : None */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* tagsData : Some */[action[0]]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
