// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Auth0Js = require("auth0-js");

var authOptions = {
  domain: "caml-flage.auth0.com",
  clientID: "NEI3vWpag1sFz5z1IoJV7U52op6HKPxb",
  redirectUri: "http://localhost:3000/callback",
  responseType: "token id_token",
  scope: "openid"
};

var authClient = new Auth0Js.WebAuth(authOptions);

exports.authOptions = authOptions;
exports.authClient = authClient;
/* authClient Not a pure module */
