// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parseCommentsJson(json) {
  return /* record */[
          /* comment_id */Json_decode.field("comment_id", Json_decode.$$int, json),
          /* text */Json_decode.field("text", Json_decode.string, json),
          /* score */Json_decode.field("score", Json_decode.$$int, json),
          /* children */Json_decode.field("children", (function (param) {
                  return Json_decode.array(parseCommentsJson, param);
                }), json)
        ];
}

function parseCommentsResponseJson(json) {
  return Json_decode.field("comment_list", (function (param) {
                return Json_decode.array(parseCommentsJson, param);
              }), json);
}

function fetchComments(postsUrl) {
  return fetch(postsUrl).then((function (prim) {
                  return prim.text();
                })).then((function (jsonText) {
                return Promise.resolve(parseCommentsResponseJson(JSON.parse(jsonText)));
              }));
}

exports.parseCommentsJson = parseCommentsJson;
exports.parseCommentsResponseJson = parseCommentsResponseJson;
exports.fetchComments = fetchComments;
/* No side effect */
