// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Title$ReactTemplate = require("./Title.bs.js");
var AllPosts$ReactTemplate = require("./AllPosts.bs.js");
var PostInput$ReactTemplate = require("./PostInput.bs.js");
var AllComments$ReactTemplate = require("./AllComments.bs.js");
var CommentInput$ReactTemplate = require("./CommentInput.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Title$ReactTemplate.make("Welcome to Caml-flage", /* array */[])), "title");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, PostInput$ReactTemplate.make("Create a new post here!", /* array */[])), "input");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, AllPosts$ReactTemplate.make("/state.json", /* array */[])), "posts");

var url = ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0);

var lst = url[/* path */0];

var post_id = List.nth(lst, List.length(lst) - 1 | 0);

var myurl = "/post/" + (post_id + "/poststate.json");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, AllPosts$ReactTemplate.make(myurl, /* array */[])), "onepost");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, AllComments$ReactTemplate.make(myurl, /* array */[])), "comments");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, CommentInput$ReactTemplate.make("Write a comment", /* array */[])), "comment_input");

exports.url = url;
exports.lst = lst;
exports.post_id = post_id;
exports.myurl = myurl;
/*  Not a pure module */
