// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Axios = require("axios");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function valueFromEvent(evt) {
  return evt.target.value;
}

var component = ReasonReact.reducerComponent("EditField");

function setInputElement(theRef, param) {
  param[/* state */2][/* inputElement */2][0] = (theRef == null) ? /* None */0 : [theRef];
  return /* () */0;
}

function make(initialText, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */4];
              var match = param[/* state */2];
              var text = match[/* text */1];
              var title = match[/* title */0];
              var handle = param[/* handle */0];
              return React.createElement("div", undefined, React.createElement("div", undefined, "Create a new post"), React.createElement("div", undefined, React.createElement("input", {
                                  ref: Curry._1(handle, setInputElement),
                                  type: "text",
                                  value: title,
                                  onChange: (function (evt) {
                                      return Curry._1(send, /* ChangeTitle */Block.__(0, [evt.target.value]));
                                    })
                                }), React.createElement("input", {
                                  ref: Curry._1(handle, setInputElement),
                                  type: "text",
                                  value: text,
                                  onChange: (function (evt) {
                                      return Curry._1(send, /* ChangeText */Block.__(1, [evt.target.value]));
                                    })
                                }), React.createElement("button", {
                                  onClick: (function () {
                                      return Curry._1(send, /* Submit */Block.__(2, [
                                                    title,
                                                    text
                                                  ]));
                                    })
                                }, "Submit")));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* title */"Title",
                      /* text */initialText,
                      /* inputElement */[/* None */0]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action) {
              switch (action.tag | 0) {
                case 0 : 
                    var newTitle = action[0];
                    console.log(newTitle);
                    return (function (state) {
                        return /* Update */Block.__(0, [/* record */[
                                    /* title */newTitle,
                                    /* text */state[/* text */1],
                                    /* inputElement */state[/* inputElement */2]
                                  ]]);
                      });
                case 1 : 
                    var newText = action[0];
                    console.log(newText);
                    return (function (state) {
                        return /* Update */Block.__(0, [/* record */[
                                    /* title */state[/* title */0],
                                    /* text */newText,
                                    /* inputElement */state[/* inputElement */2]
                                  ]]);
                      });
                case 2 : 
                    Axios.post("/post", {
                              user_id: "",
                              title: action[0],
                              text: action[1]
                            }).then((function (response) {
                              return Promise.resolve((console.log(response.data), /* () */0));
                            })).catch((function (error) {
                            return Promise.resolve((console.log(error), /* () */0));
                          }));
                    return (function (state) {
                        return /* Update */Block.__(0, [/* record */[
                                    /* title */"Post made!",
                                    /* text */"",
                                    /* inputElement */state[/* inputElement */2]
                                  ]]);
                      });
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.valueFromEvent = valueFromEvent;
exports.component = component;
exports.setInputElement = setInputElement;
exports.make = make;
/* component Not a pure module */
