// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var parseTagsJson = Json_decode.string;

function parseTagsResponseJson(json) {
  return Json_decode.field("tags", (function (param) {
                return Json_decode.array(parseTagsJson, param);
              }), json);
}

function fetchTags(tagsUrl) {
  return fetch(tagsUrl).then((function (prim) {
                  return prim.text();
                })).then((function (jsonText) {
                return Promise.resolve(parseTagsResponseJson(JSON.parse(jsonText)));
              }));
}

exports.parseTagsJson = parseTagsJson;
exports.parseTagsResponseJson = parseTagsResponseJson;
exports.fetchTags = fetchTags;
/* No side effect */
